{% set name = "qibolab" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibolab/archive/v{{ version }}.tar.gz
  sha256: 1d6462e374da8670aa4671dbf7f35d6f56b33c1f3cc900e9aa5664ea41225088

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }},<3.12
    - qibo >=0.1.8
    - more-itertools
    - networkx
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - qibolab

about:
  home: https://github.com/qiboteam/qibolab
  summary: Quantum hardware module and drivers for Qibo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
